services:
  proxy:
    image: traefik:3.6
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=http"

  prestart:
    image: backend:latest
    networks:
      - default
    depends_on:
      - db
      - backend
    env_file:
      - ./backend/docker.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    command: >
      bash -c "
        echo '--- Running Alembic migrations ---' &&
        alembic upgrade head &&
        echo '--- Checking for initial data ---' &&
        python /app/app/db/initial_data.py
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # <-- Restauramos este volumen para la sincronización de ficheros
      - /app/.venv
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    env_file:
      - ./backend/docker.env
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))"
      - "traefik.http.routers.backend.entrypoints=http"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    image: postgres:16-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/
    networks:
      - default
    env_file:
      - ./backend/docker.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./docker.env
    networks:
      - traefik-public
      - default
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=http"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - default

volumes:
  app-db-data:

networks:
  traefik-public:
    external: true
  default:
    driver: bridge