# This is a Render Blueprint file.
# It defines the services and infrastructure for the IvanInTech project.
# To deploy, go to https://dashboard.render.com/blueprints and connect your repo.
# For more details, see: https://render.com/docs/blueprint-spec

# Databases are defined at the top level in the modern spec.
databases:
  - name: ivanintech-db
    databaseName: ivanintech_db
    user: ivanintech_user
    plan: free # 'starter' is a good paid alternative.
    postgresMajorVersion: 15

services:
  # 1. Backend Service (FastAPI)
  # ----------------------------
  - type: web
    name: backend
    runtime: python # The correct property is 'runtime'
    rootDir: ./backend
    buildCommand: |
      pip install --upgrade pip
      pip install .
      # Run Alembic migrations on every deploy.
      alembic upgrade head
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ivanintech-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SERVER_HOST
        value: "0.0.0.0" # Important for Render to bind correctly
    # Environment groups are linked at the service level like this.
    envVarGroups:
      - ivanintech-secrets

  # 2. Frontend Service (Next.js)
  # -----------------------------
  - type: web
    name: frontend
    runtime: node # The correct property is 'runtime'
    rootDir: ./frontend
    buildCommand: |
      npm install
      npm run build
    startCommand: "npm start"
    envVars:
      # The correct variable name used by the frontend code is NEXT_PUBLIC_API_BASE_URL.
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
      - key: NEXT_PUBLIC_APP_NAME
        value: "IvanInTech"
    # Routing rules to direct /api/* traffic to the backend.
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: /api/$1
        service:
          type: web
          name: backend

# Note on Secrets:
# The `ivanintech-secrets` group should contain the following variables
# which you must set in the Render dashboard under "Environment":
# - SECRET_KEY
# - GNEWS_API_KEY
# - EVENT_REGISTRY_API_KEY
# - GOOGLE_API_KEY
# - GOOGLE_CSE_ID
# - FIRST_SUPERUSER
# - FIRST_SUPERUSER_PASSWORD 