# render.yaml
# Defines all services, databases, and environment variables for the project.
# See https://render.com/docs/blueprint-spec for details.

databases:
  # Creates a PostgreSQL database on the free plan.
  - name: ivanintech-db
    plan: free

services:
  # 1. Backend Service (FastAPI)
  # This service runs the Python backend application.
  - type: web
    name: ivanintech-backend
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ivanintech-db
          property: connectionString
      - key: PROJECT_NAME
        value: ivanintech
      - key: STACK_NAME
        value: ivanintech
      - key: MODULE_NAME
        value: app.main
      - key: VARIABLE_NAME
        value: app
      - key: FIRST_SUPERUSER
        generateValue: true
      - key: FIRST_SUPERUSER_PASSWORD
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: SENTRY_DSN
        value: https://c1e7935a51982b545f1c4e7a27a81414@o4507005085483008.ingest.us.sentry.io/4507005088235520
      - key: GOOGLE_API_KEY
        sync: false
    buildCommand: "pip install --upgrade pip && pip install -r backend/requirements.txt && python backend/app/db/seed_db.py reset"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true

  # 2. Frontend Service (Next.js)
  # This service runs the Next.js frontend and handles user traffic.
  - type: web
    name: frontend
    runtime: node
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      # This variable gets the public URL of the backend service for API calls.
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: ivanintech-backend
          property: url
      # --- IMPORTANT: FIREBASE SECRETS ---
      # You MUST set values for these keys in the Render Dashboard.
      # Go to your 'frontend' service -> 'Environment' tab and add them.
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID # Optional

# This block defines a group of secrets that can be shared across services.
# You must set the values for these keys in the Render Dashboard
# under Environment > Environment Groups.
envVarGroups:
  - name: ivanintech-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure random value
      - key: GNEWS_API_KEY
      - key: EVENT_REGISTRY_API_KEY
      - key: GOOGLE_API_KEY
      - key: FIRST_SUPERUSER
      - key: FIRST_SUPERUSER_PASSWORD