"""Add user relationship to NewsItem

Revision ID: 8a7d6e5c4b3f
Revises: 9c3c759fa74d
Create Date: 2024-07-20 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7d6e5c4b3f'
down_revision: Union[str, None] = '9c3c759fa74d' # Apunta a la última migración real
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_news_items_submitted_by_user_id_user',
            'user',
            ['submitted_by_user_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_items_submitted_by_user_id_user', type_='foreignkey')
        batch_op.drop_column('submitted_by_user_id')
    # ### end Alembic commands ### 