"""Add timezone to resource_votes created_at

Revision ID: 9f6654de1ec5
Revises: dfa5ec2e84d4
Create Date: 2025-06-18 03:35:28.294238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6654de1ec5'
down_revision: Union[str, None] = 'dfa5ec2e84d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    # op.drop_table('apscheduler_jobs')

    # Fix existing NULL values before applying the NOT NULL constraint
    op.execute('UPDATE news_items SET is_community = False WHERE is_community IS NULL')
    op.execute('UPDATE news_items SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL')
    
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=False)
        batch_op.alter_column('is_community',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.alter_column('is_community',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
        batch_op.alter_column('updated_at',
                   existing_type=sa.DATETIME(),
                   nullable=True)
    # op.create_table('apscheduler_jobs',
    # sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    # sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    # sa.Column('job_state', sa.BLOB(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
