"""Merge real heads

Revision ID: b5a3e9c8d7f6
Revises: 0679ddf92335, 8a7d6e5c4b3f
Create Date: 2024-07-21 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a3e9c8d7f6'
down_revision: Union[str, None] = ('0679ddf92335', '8a7d6e5c4b3f')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 