"""Make published_date nullable in blog_posts

Revision ID: e38e15120cf7
Revises: c17eb5ad47eb
Create Date: 2025-06-23 11:23:48.799697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38e15120cf7'
down_revision: Union[str, None] = 'c17eb5ad47eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('published_date',
                   existing_type=sa.DATE(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('published_date',
                   existing_type=sa.DATE(),
                   nullable=False)
    # ### end Alembic commands ###
