"""Crear esquema inicial desde modelos

Revision ID: e6dae46581af
Revises: 9f0346115888
Create Date: 2025-06-15 21:51:55.221965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e6dae46581af'
down_revision: Union[str, None] = '9f0346115888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_news_items')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('news_items', 'is_community',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_items', 'is_community',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('_alembic_tmp_news_items',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('publishedAt', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('imageUrl', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('relevance_score', sa.INTEGER(), nullable=True),
    sa.Column('sectors', sqlite.JSON(), nullable=True),
    sa.Column('sourceName', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sourceId', sa.VARCHAR(length=255), nullable=True),
    sa.Column('star_rating', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_community', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
