"""Add status and linkedin url to blog posts, add user relation

Revision ID: 2ab7c675de7f
Revises: 962ac8c25663
Create Date: 2025-05-04 00:35:38.825543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab7c675de7f'
down_revision: Union[str, None] = '962ac8c25663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('published_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('linkedin_post_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='published'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_status'), ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_blog_posts_author_id_user'), 'user', ['author_id'], ['id'])
        batch_op.drop_column('date')
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('imageUrl', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_blog_posts_author_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_posts_status'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('status')
        batch_op.drop_column('linkedin_post_url')
        batch_op.drop_column('image_url')
        batch_op.drop_column('tags')
        batch_op.drop_column('last_modified_date')
        batch_op.drop_column('published_date')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
