"""Add sourceName and sourceId to NewsItem model

Revision ID: 78f8d67384af
Revises: e71687c8e63a
Create Date: 2025-05-03 20:22:56.285440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f8d67384af'
down_revision: Union[str, None] = 'e71687c8e63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjust for SQLite batch mode ###
    # --- Batch Block 1: Add new columns ---    
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sourceName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sourceId', sa.String(length=255), nullable=True))

    # --- Batch Block 2: Other modifications ---    
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.alter_column('imageUrl',
                   existing_type=sa.VARCHAR(length=1000),
                   type_=sa.String(length=1024),
                   existing_nullable=True)
        batch_op.drop_index('ix_news_items_source')
        batch_op.drop_column('summary')
        batch_op.drop_column('source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjust for SQLite batch mode ###
    # --- Batch Block 1 (Reverse): Other modifications --- 
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.create_index('ix_news_items_source', ['source'], unique=False)
        batch_op.alter_column('imageUrl',
                   existing_type=sa.String(length=1024),
                   type_=sa.VARCHAR(length=1000),
                   existing_nullable=True)
                   
    # --- Batch Block 2 (Reverse): Remove added columns --- 
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_column('sourceId')
        batch_op.drop_column('sourceName')
    # ### end Alembic commands ###
