"""Reconcile schema after partial 78f8d67384af application

Revision ID: 962ac8c25663
Revises: 78f8d67384af
Create Date: 2025-05-03 20:41:31.626622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962ac8c25663'
down_revision: Union[str, None] = '78f8d67384af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.alter_column('imageUrl',
                   existing_type=sa.VARCHAR(length=1000),
                   type_=sa.String(length=1024),
                   existing_nullable=True)
        batch_op.drop_index('ix_news_items_source') # No need for table_name inside batch
        batch_op.drop_column('source')
        batch_op.drop_column('summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_news_items_source', ['source'], unique=False)
        batch_op.alter_column('imageUrl',
                   existing_type=sa.String(length=1024),
                   type_=sa.VARCHAR(length=1000),
                   existing_nullable=True)
    # ### end Alembic commands ###
