"""Change BlogPost id to String

Revision ID: e71687c8e63a
Revises: bda0e2313b0e
Create Date: 2025-05-03 16:37:15.818089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71687c8e63a'
down_revision: Union[str, None] = 'bda0e2313b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('id',
                existing_type=sa.INTEGER(),
                type_=sa.String(length=100),
                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.alter_column('id',
                existing_type=sa.String(length=100),
                type_=sa.INTEGER(),
                existing_nullable=False)
    # ### end Alembic commands ###
